-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 13:38:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restolerance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restolerance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restolerance` DEFAULT CHARACTER SET utf8 ;
USE `Restolerance` ;

-- -----------------------------------------------------
-- Table `Restolerance`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restolerance`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(80) NOT NULL,
  `firstname` VARCHAR(80) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(15) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `usertype` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueUser` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restolerance`.`plates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restolerance`.`plates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniquePlate` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restolerance`.`intolerances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restolerance`.`intolerances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueIntolerance` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restolerance`.`plates_contain_intolerances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restolerance`.`plates_contain_intolerances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plate_id` INT NOT NULL,
  `intolerance_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plates_has_intolerances_intolerances1_idx` (`intolerance_id` ASC) VISIBLE,
  INDEX `fk_plates_has_intolerances_plates_idx` (`plate_id` ASC) VISIBLE,
  UNIQUE INDEX `UniqueContain` (`plate_id` ASC, `intolerance_id` ASC) INVISIBLE,
  CONSTRAINT `fk_plates_has_intolerances_plates`
    FOREIGN KEY (`plate_id`)
    REFERENCES `Restolerance`.`plates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plates_has_intolerances_intolerances1`
    FOREIGN KEY (`intolerance_id`)
    REFERENCES `Restolerance`.`intolerances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restolerance`.`users_select_intolerances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restolerance`.`users_select_intolerances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `intolerance_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_intolerances_intolerances1_idx` (`intolerance_id` ASC) VISIBLE,
  INDEX `fk_users_has_intolerances_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `UniqueSelect` (`user_id` ASC, `intolerance_id` ASC) INVISIBLE,
  CONSTRAINT `fk_users_has_intolerances_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Restolerance`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_intolerances_intolerances1`
    FOREIGN KEY (`intolerance_id`)
    REFERENCES `Restolerance`.`intolerances` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restolerance`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restolerance`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueOrder` (`id` ASC) VISIBLE,
  INDEX `fk_orders_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Restolerance`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restolerance`.`plates_contain_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restolerance`.`plates_contain_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT(3) NOT NULL,
  `plate_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plates_has_orders_orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_plates_has_orders_plates1_idx` (`plate_id` ASC) VISIBLE,
  INDEX `UniqueContain` (`plate_id` ASC, `order_id` ASC) VISIBLE,
  CONSTRAINT `fk_plates_has_orders_plates1`
    FOREIGN KEY (`plate_id`)
    REFERENCES `Restolerance`.`plates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plates_has_orders_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `Restolerance`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Datas `Restolerance`.`intolerances`
-- -----------------------------------------------------
INSERT INTO intolerances (id, name) VALUES (1, 'Dairy'),
 (2, 'Gluten'),
 (3, 'Caffeine'),
 (4, 'Salicylates'),
 (5, 'Amines'),
 (6, 'FODMAPs'),
 (7, 'Sulfites'),
 (8, 'Fructose'),
 (9, 'Aspartame'),
 (10, 'Eggs'),
 (11, 'MSG'),
 (12, 'Food colorings'),
 (13, 'Yeast'),
 (14, 'Sugar alcohols');


-- -----------------------------------------------------
-- Datas `Restolerance`.`plates`
-- -----------------------------------------------------
INSERT INTO plates (id, name, description, price, image) VALUES (1, 'Tagliatelles au boeuf', 'Ce délicieux plat de tagliatelles vous sera servi accompagné de ses petits morceaux de viande ainsi que ses quelques légumes.', 25.00, 'view/img/pates.jpg'),
(2, 'Riz frit indonésien aux légumes', 'Le Nasi Goreng, un plat typique d’Indonésie, aussi appelé Riz Frit. Il est complet avec le riz, les légumes et la protéine.', 28.00, 'view/img/riz.jpg'),
(3, 'Couscous', 'Ce couscous, d’origine marocaine, est ici accompagné de viande de mouton, de la semoule de blé et un choix varié de légumes et de légumineuses.', 31.00, 'view/img/couscous.jpg'),
(4, 'Filets de perche meunières', 'Les filets de perche, incontournable des poissons, vous sont servis accompagnés de leur delicieuse sauce tartare, légumes, ainsi qu’une portion de frites.', 29.00, 'view/img/filetsDePerche.jpg'),
(5, 'Paëlla', 'Ce plat traditionnel espagnol, est la description même du plat de fête. Concu à l’aide de nombreux aliments tel que du riz, des fruits de mer et sa dose de légumes sains nous ne pouvons que vous conseiller de l’essayer !', 32.00, 'view(img/paella.jpg'),
(6, 'Feijoada', 'La feijoada est un plat très populaire particulièrement au Brésil et au Portugal. Elle consiste en un ragoût de haricots noirs, servi avec de la viande et du riz blanc.', 26.00, 'view/img/feijoada.jpg'),
(7, 'Bortsch', 'Le bortsch, est un potage nous venant des pays slaves. Il contient, chez nous, de la betterave, du chou, des carrotes, des pommes de terre et des oignons.', 25.00, 'view/img/bortsch.jpg');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;